# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Actdocs < Formula
  desc "actdocs 0.6.0"
  homepage "https://github.com/tmknom/actdocs"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmknom/actdocs/releases/download/v0.6.0/actdocs_0.6.0_darwin_amd64"
      sha256 "e00070890015758cc256eb3501befd985f919767ded3a7f742492f63a9398ac5"

      def install
        bin.install "actdocs_0.6.0_darwin_amd64" => "actdocs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmknom/actdocs/releases/download/v0.6.0/actdocs_0.6.0_darwin_arm64"
      sha256 "aa8a100f016765ae2b5e9c2ee8090d77009ccc452b1e4bbff43ac19c09bd1e61"

      def install
        bin.install "actdocs_0.6.0_darwin_arm64" => "actdocs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/actdocs/releases/download/v0.6.0/actdocs_0.6.0_linux_amd64"
        sha256 "b0c014ef22df2ce3143c58bea5f8f3110b0008c5b4c8370edbe91e9de482429d"

        def install
          bin.install "actdocs_0.6.0_linux_amd64" => "actdocs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/actdocs/releases/download/v0.6.0/actdocs_0.6.0_linux_arm64"
        sha256 "08b4347effbddec23ab7d41a3d3ee2f560013e1aa694e02c0cea8ac861e85224"

        def install
          bin.install "actdocs_0.6.0_linux_arm64" => "actdocs"
        end
      end
    end
  end

  test do
    system "#{bin}/actdocs --version"
  end
end
