# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valid < Formula
  desc "valid 0.2.3"
  homepage "https://github.com/tmknom/valid"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmknom/valid/releases/download/v0.2.3/valid_0.2.3_darwin_amd64"
      sha256 "f80af52e355476546133780356e8c947c6c232ba083fac2b31189f39cbb1a02b"

      def install
        bin.install "valid_0.2.3_darwin_amd64" => "valid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmknom/valid/releases/download/v0.2.3/valid_0.2.3_darwin_arm64"
      sha256 "a627dd43fa445e34b53648c1f5dde9135f35bda0440a8565ec464a75c473cd9a"

      def install
        bin.install "valid_0.2.3_darwin_arm64" => "valid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/valid/releases/download/v0.2.3/valid_0.2.3_linux_amd64"
        sha256 "bd757cec83e683e0c365304eef45700ba602d019524cbf250ea44e4490d59aee"

        def install
          bin.install "valid_0.2.3_linux_amd64" => "valid"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/valid/releases/download/v0.2.3/valid_0.2.3_linux_arm64"
        sha256 "216036d709a4d96e53c62f5429bbf2da6025f2d2440d8b8b52a758ff1709f081"

        def install
          bin.install "valid_0.2.3_linux_arm64" => "valid"
        end
      end
    end
  end

  test do
    system "#{bin}/valid --version"
  end
end
