# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valid < Formula
  desc "valid 0.6.1"
  homepage "https://github.com/tmknom/valid"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmknom/valid/releases/download/v0.6.1/valid_0.6.1_darwin_amd64"
      sha256 "deeeb721a55745c0180a2fa2881113f6a3cce5a6b0cf81f095c18f8945731e9b"

      def install
        bin.install "valid_0.6.1_darwin_amd64" => "valid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmknom/valid/releases/download/v0.6.1/valid_0.6.1_darwin_arm64"
      sha256 "689c7d6f7bb0aa9ea7a775851ad8785b5e8b7c6409d675d7e1717bdc3de66a3a"

      def install
        bin.install "valid_0.6.1_darwin_arm64" => "valid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/valid/releases/download/v0.6.1/valid_0.6.1_linux_amd64"
        sha256 "70841b708176d796eab1708f4f81a29a570319405fce308bc4ea91363cad9231"

        def install
          bin.install "valid_0.6.1_linux_amd64" => "valid"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/valid/releases/download/v0.6.1/valid_0.6.1_linux_arm64"
        sha256 "87c5ac74459f2bd9d277f970a689baa2081bb55db1845d04f5f42ec63f08448d"

        def install
          bin.install "valid_0.6.1_linux_arm64" => "valid"
        end
      end
    end
  end

  test do
    system "#{bin}/valid --version"
  end
end
