# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valid < Formula
  desc "valid 0.3.1"
  homepage "https://github.com/tmknom/valid"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmknom/valid/releases/download/v0.3.1/valid_0.3.1_darwin_amd64"
      sha256 "fc1d1d7fbff34bc375d331461c834da48f6d02aab29e9ab80007574082805a9a"

      def install
        bin.install "valid_0.3.1_darwin_amd64" => "valid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmknom/valid/releases/download/v0.3.1/valid_0.3.1_darwin_arm64"
      sha256 "388ab13761e4cf539bf268d9a576e3e2b653e2f3cce1699c4078c5020ce2ff8b"

      def install
        bin.install "valid_0.3.1_darwin_arm64" => "valid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/valid/releases/download/v0.3.1/valid_0.3.1_linux_amd64"
        sha256 "da8d1211dcd29677977a360a17c6823a90c3960474528e558e2f254193cf9335"

        def install
          bin.install "valid_0.3.1_linux_amd64" => "valid"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/valid/releases/download/v0.3.1/valid_0.3.1_linux_arm64"
        sha256 "7e621726a8d1a7a83c8ac53d98f13c76584e3eb93025c0db63c58b8ecb515a03"

        def install
          bin.install "valid_0.3.1_linux_arm64" => "valid"
        end
      end
    end
  end

  test do
    system "#{bin}/valid --version"
  end
end
